default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # These will be read from the environment variables in docker-compose.yml
  host: <%= ENV.fetch("DATABASE_HOST") { 'localhost' } %>
  username: <%= ENV.fetch("DATABASE_USER") { '' } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { '' } %>

development:
  <<: *default
  database: Budgy_development

test:
  <<: *default
  database: Budgy_test

# For production, we will use a single DATABASE_URL for simplicity and security.
# This is the standard for platforms like Heroku.
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>